# Generated by Django 3.0.4 on 2020-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200329_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='grno',
            field=models.IntegerField(unique=True),
        ),
    ]
