# Generated by Django 3.0.4 on 2020-03-31 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_auto_20200329_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('Text book', 'Text book'), ('Long note', 'Long note'), ('Short note', 'Short note'), ('Lab record', 'Lab Record'), ('Graph book', 'Graph book')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
