# Generated by Django 3.0.4 on 2020-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200331_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=7),
        ),
    ]
