# Generated by Django 3.0.4 on 2020-03-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemestry', 'Chemestry'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('Social Studies', 'Social Studies'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], max_length=100)),
                ('book_type', models.CharField(choices=[('Text book', 'Text book'), ('Long note book', 'Long note book'), ('Short note book', 'Short note book')], max_length=100)),
                ('garde', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('All', 'All')], max_length=100)),
                ('stock', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
