# Generated by Django 3.0.4 on 2020-03-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='book_name',
            new_name='book',
        ),
    ]
