# Generated by Django 3.0.4 on 2020-03-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('Social Studies', 'Social Studies'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], max_length=100),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book_type', models.CharField(default='', editable=False, max_length=100)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
