# Generated by Django 3.0.4 on 2020-03-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200329_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='garde',
            new_name='grade',
        ),
    ]
