# Generated by Django 3.0.4 on 2020-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200327_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='book_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
