# Generated by Django 3.0.4 on 2020-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_log_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='book_type',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
