# Generated by Django 3.0.4 on 2020-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200331_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('Added to cart', 'Added to cart'), ('Removed from cart', 'Removed from cart'), ('Bought', 'Bought')], default='Added to cart', max_length=100),
        ),
    ]
