# Generated by Django 3.0.4 on 2020-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200331_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('Bought', 'Bought')], max_length=100),
        ),
    ]
