# Generated by Django 3.0.4 on 2020-03-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200331_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='action',
        ),
    ]
